import { Dimensions, StyleSheet, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7F9F9",
  },
  map: {
    flex: 1,
  },
  buttonContainer: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? height * 0.1 : height * 0.08,
    left: width * 0.05,
    right: width * 0.05,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  button: {
    flex: 1,
    backgroundColor: "#2196F3",
    marginHorizontal: width * 0.01,
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.1,
    borderRadius: width * 0.05,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  buttonText: {
    fontSize: width * 0.04,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  imageBubble: {
    position: "absolute",
    top: height * 0.06,
    left: width * 0.05,
    width: width * 0.23,
    height: height * 0.093,
    backgroundColor: "#fff",
    borderRadius: width * 0.02,
    padding: width * 0.01,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  imageText: {
    fontSize: width * 0.02,
    fontWeight: "bold",
    marginBottom: height * 0.005,
  },
  mapPreview: {
    width: width * 0.2,
    height: height * 0.07,
    borderRadius: width * 0.05,
  },
  activityIndicator: {
    position: "absolute",
    top: height * 0.15,
    left: width * 0.5 - 25,
  },
  loadingHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingVertical: height * 0.01,
    paddingHorizontal: width * 0.2,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 10,
    height: height * 0.09,
  },

  loadingText: {
    color: "#ffffff",
    fontSize: width * 0.05,
    marginLeft: width * 0.025,
  },
  restoreButton: {
    position: "absolute",
    bottom: height * 0.2,
    left: "25%",
    right: "25%",
    backgroundColor: "blue",
    padding: width * 0.03,
    borderRadius: width * 0.05,
    alignItems: "center",
    justifyContent: "center",
  },
});
